### ISSUE TITLE
Client-Spec: Umbrella issue for all TODOs

### ISSUE THREAD

**Issue by tracymiranda** [sigstore/architecture-docs#12]
**Description**

This issue is the umbrella issue that lists all the pending todos for when the spec was migrated from google docs to markdown (in same order as they appear in the doc)
- [ ] #10 
- [ ] #11 
- [ ] Review 3.1 Signing Choices repetitiveness with earlier sections ([link](https://docs.google.com/document/d/1kbhK2qyPPk8SLavHzYSDM8-Ueul9_oxIMVFuWMWKz0E/edit?disco=AAAAtyvALJU))
- [ ] 4.1 Inputs: consider strengthening language substantially ([link](https://docs.google.com/document/d/1kbhK2qyPPk8SLavHzYSDM8-Ueul9_oxIMVFuWMWKz0E/edit?disco=AAABQVV-gT0))
- [ ] 4.2 do we need to [include the note to implementers](https://docs.google.com/document/d/1kbhK2qyPPk8SLavHzYSDM8-Ueul9_oxIMVFuWMWKz0E/edit?disco=AAABCrCkr8E)?
- [ ] 4.3 Resolve [comment](https://docs.google.com/document/d/1kbhK2qyPPk8SLavHzYSDM8-Ueul9_oxIMVFuWMWKz0E/edit?disco=AAAAtyvALfU)
- [ ] 4.3 Consider adding something on if no time is available ([link](https://docs.google.com/document/d/1kbhK2qyPPk8SLavHzYSDM8-Ueul9_oxIMVFuWMWKz0E/edit?disco=AAAAtyvALMs))
- [ ] 4.3 Consider mentioning verifying other OID claims for CI/CD platforms ([link](https://docs.google.com/document/d/1kbhK2qyPPk8SLavHzYSDM8-Ueul9_oxIMVFuWMWKz0E/edit?disco=AAAAtyvALMs))
- [ ] 4.3 Update section to mandate verifying inclusion proofs ([link](https://docs.google.com/document/d/1kbhK2qyPPk8SLavHzYSDM8-Ueul9_oxIMVFuWMWKz0E/edit?disco=AAAA3TpGAt0))
- [ ] #8
