### ISSUE TITLE
Rekor Spec: Umbrella issue for all TODOs

### ISSUE THREAD

**Issue by tracymiranda** [sigstore/architecture-docs#30]
**Description**
This is a list of the unresolved TODOs from the original [Google Doc](https://docs.google.com/document/d/1NQUBSL9R64_vPxUEgVKGb0p81_7BVZ7PQuI078WFn-g/edit?tab=t.0#heading=h.6w69n885z90t) to be resolved before archiving that doc. Listed in order of comments in the doc

- [ ] Section 2. Clarify what the MAY clause for signing key for an entry ([comment](https://docs.google.com/document/d/1NQUBSL9R64_vPxUEgVKGb0p81_7BVZ7PQuI078WFn-g/edit?disco=AAABBDhaXfc))
- [ ] Section 2. Clarify paragraph about storage of signing events ([comment1](https://docs.google.com/document/d/1NQUBSL9R64_vPxUEgVKGb0p81_7BVZ7PQuI078WFn-g/edit?disco=AAABDYgH0yo), [comment2](https://docs.google.com/document/d/1NQUBSL9R64_vPxUEgVKGb0p81_7BVZ7PQuI078WFn-g/edit?disco=AAABEnR97DU))
- [ ] Section 2 Address question about witnessing list ([comment](https://docs.google.com/document/d/1NQUBSL9R64_vPxUEgVKGb0p81_7BVZ7PQuI078WFn-g/edit?disco=AAABBDhaXgU))
- [ ] Section 3: Make architecture section more descriptive/readable ([comment](https://docs.google.com/document/d/1NQUBSL9R64_vPxUEgVKGb0p81_7BVZ7PQuI078WFn-g/edit?disco=AAABBGiJqBo))
- [ ] Section 4: Make terminology consistent, consider moving to shared glossary ([comment](https://docs.google.com/document/d/1NQUBSL9R64_vPxUEgVKGb0p81_7BVZ7PQuI078WFn-g/edit?disco=AAABBDhaXlA))
- [ ] Section 4: Address terminology comments ([comment1](https://docs.google.com/document/d/1NQUBSL9R64_vPxUEgVKGb0p81_7BVZ7PQuI078WFn-g/edit?disco=AAABBDhaXms), [comment2](https://docs.google.com/document/d/1NQUBSL9R64_vPxUEgVKGb0p81_7BVZ7PQuI078WFn-g/edit?disco=AAAA3vaOuGw), [comment3](https://docs.google.com/document/d/1NQUBSL9R64_vPxUEgVKGb0p81_7BVZ7PQuI078WFn-g/edit?disco=AAAA4_YeiT0), [comment4](https://docs.google.com/document/d/1NQUBSL9R64_vPxUEgVKGb0p81_7BVZ7PQuI078WFn-g/edit?disco=AAABBDhaXo0))
